export const projects = [
  {
    id: 1,
    image: "./Projects/EpicTravel.png",
    title: "Epic Travel Landing Page",
    category: "Frontend",
    description: "A visually appealing travel landing page designed to attract travelers with an engaging layout and responsive design.",
    liveLink: "https://atiqueshahriarr.github.io/Travel-Landing-Page/",
    codeLink: "https://github.com/atiqueshahriarr/Travel-Landing-Page",
    toolsIcons: ["./Skills/HTML5.png", "./Skills/CSS3.png"],
    toolsNames: ["HTML", "CSS"],
    features: ["Attractive UI/UX design", "Fully responsive layout", "Smooth scrolling experience", "Clear call-to-action buttons"],
    duration: "2 Days",
  },
  {
    id: 2,
    image: "./Projects/HeritageNest.png",
    title: "Heritage Nest",
    category: "Frontend",
    description: "A four-page website featuring a home page, product page, product details page, and about page with seamless navigation.",
    liveLink: "https://heritagenestt.netlify.app/",
    codeLink: "https://github.com/atiqueshahriarr/HeritageNest",
    toolsIcons: ["./Skills/Tailwind CSS.png", "./Skills/React.png"],
    toolsNames: ["Tailwind CSS", "React"],
    features: ["Multi-page navigation", "Dynamic product details page", "Responsive and user-friendly interface", "Interactive footer with quick access links"],
    duration: "3 Days",
  },
  {
    id: 3,
    image: "./Projects/E-Ticketing.png",
    title: "E-Ticketing",
    category: "Frontend",
    description: "The E-Ticketing landing page provides a seamless experience where users can easily select their preferred seats and apply coupons.",
    liveLink: "https://e-ticketing24.netlify.app/",
    codeLink: "https://github.com/atique-shahriar/E-Ticketing-Website",
    toolsIcons: ["./Skills/Tailwind CSS.png", "./Skills/React.png"],
    toolsNames: ["Tailwind CSS", "React"],
    features: ["Seat selection system", "Coupon code functionality", "Responsive design", "User-friendly interface"],
    duration: "3 Days",
  },
  {
    id: 4,
    image: "./Projects/Land-Spark.png",
    title: "Land Spark",
    category: "Frontend",
    description: "Land Spark displays property with personalized access to details and management, enhancing user experiences.",
    liveLink: "https://land-spark-react-project.web.app/",
    codeLink: "https://github.com/atique-shahriar/LandSpark",
    toolsIcons: ["./Skills/Tailwind CSS.png", "./Skills/React.png", "./Skills/Firebase.png"],
    toolsNames: ["Tailwind CSS", "React", "Firebase"],
    features: ["Showcases property listings with key details.", "Secure login/signup with Firebase authentication.", "Personalized recommendations for logged-in users.", "User profile creation and management.", "Detailed property info for authenticated users."],
    duration: "5 Days",
  },
  {
    id: 5,
    image: "./Projects/Travel-Planner.png",
    title: "Travel Planner",
    category: "Fullstack",
    description: "Travel Planner provides an intuitive interface for seamless trip planning for personalized travel experiences.",
    liveLink: "https://travel-planner-70a42.web.app/",
    codeLink: "https://github.com/atique-shahriar/TravelPlanner_Client",
    toolsIcons: ["./Skills/Tailwind CSS.png", "./Skills/React.png", "./Skills/Firebase.png", "./Skills/Node.js.png", "./Skills/Express.png", "./Skills/MongoDB.png"],
    toolsNames: ["Tailwind CSS", "React", "Firebase", "Node.js", "Express", "MongoDB"],
    features: ["Secure login/signup with Firebase authentication.", "Dark and light theme customization.", "Add, update, and delete tourist spots.", "View detailed tourist spot information.", "Explore country-specific travel insights.", "Sort destinations by cost for budget planning."],
    duration: "6 Days",
  },
  {
    id: 6,
    image: "./Projects/Stay-Inn.png",
    title: "Stay Inn",
    category: "Fullstack",
    description: "Room booking platform ensuring effortless reservations, secure management, and insightful guest reviews.",
    liveLink: "https://stayinn-3d14d.web.app/",
    codeLink: "https://github.com/atique-shahriar/StayInn-Client",
    toolsIcons: ["./Skills/Tailwind CSS.png", "./Skills/React.png", "./Skills/Firebase.png", "./Skills/Node.js.png", "./Skills/Express.png", "./Skills/MongoDB.png"],
    toolsNames: ["Tailwind CSS", "React", "Firebase", "Node.js", "Express", "MongoDB"],
    features: [
      "Seamless room booking with a few clicks.",
      "Flexible booking updates and cancellations.",
      "User reviews and ratings for informed decisions.",
      "Comprehensive room details and availability.",
      "Secure Firebase authentication for user access.",
      "JWT token-based authentication for session security.",
    ],
    duration: "8 Days",
  },
  {
    id: 7,
    image: "./Projects/Contest-Hub.png",
    title: "Contest Hub",
    category: "Fullstack",
    description: "Contest platform with management tools, easy entry, and secure login/payment systems for personalized profiles.",
    liveLink: "https://contesthub-fa697.web.app/",
    codeLink: "https://github.com/atique-shahriar/ContestHub_Client",
    toolsIcons: ["./Skills/Tailwind CSS.png", "./Skills/React.png", "./Skills/Firebase.png", "./Skills/Node.js.png", "./Skills/Express.png", "./Skills/MongoDB.png"],
    toolsNames: ["Tailwind CSS", "React", "Firebase", "Node.js", "Express", "MongoDB"],
    features: [
      "Personalized dashboards for admins, creators, users.",
      "Admin: block/unblock users, edit profiles, promote users.",
      "Contest management: confirm, edit, remove contests.",
      "Contest creation: add, edit, delete contests.",
      "Winner declaration: creators announce winners.",
      "Contest participation: browse, filter, and enter contests.",
      "Secure payment system for entry fees.",
    ],

    duration: "12 Days",
  },
];
